#!/bin/bash
INTERFACE=$1
STATUS=$2

restart_btsync() {
    
    USERNAME=$1
    
    if [[ "$INTERFACE" == "tun0" ]]; then
        exec systemctl restart btsync@"$USERNAME"
    else
        case "$STATUS" in
            'up') 
                exec systemctl start btsync@"$USERNAME";;
            'down') 
                exec systemctl stop btsync@"$USERNAME";;
        esac
    fi
}

getent passwd | while IFS=: read name trash
do
    groups "$name" | cut -f2 -d: | grep -q -w "btsync-users" && restart_btsync "$name"
done
